FIDO metadata
TeskaLabs/seacat-auth pull request #256
Opened 2023-09-04 11:20 UTC by byewokko

2023-10-04 15:48 UTC, byewokko commented on seacatauth/authn/webauthn/service.py
> +	async def _load_fido_metadata(self, speculative=True):
- save the metadata in mongo collection
- load on startup if collection empty
- refresh on housekeeping

- alternatively save the JWT in /tmp and store the ETag

2023-10-05 13:16 UTC, byewokko commented on seacatauth/authn/webauthn/service.py
> +	async def _load_fido_metadata(self, speculative=True):
there is no ETag available

2023-10-06 11:15 UTC, ateska requested changes

2023-10-06 11:15 UTC, ateska commented on seacatauth/authn/webauthn/service.py
> +		if speculative:
`speculative` -> `only_if_empty`

2023-10-06 11:15 UTC, ateska commented on seacatauth/authn/webauthn/service.py
> +		result = await coll.bulk_write(bulk)
This should be done atomically.

2023-10-06 13:45 UTC, merged