two stage build Dockerfile added
TeskaLabs/seacat-auth pull request #31
Opened 2022-05-05 20:25 UTC by sedoy26

2022-05-06 07:43 UTC, byewokko requested changes
@sedoy26 Could you please add the image sizes before and after, just for information? Just add it to the PR description or comment.

2022-05-06 07:43 UTC, byewokko commented on Dockerfile.test
> +# && apk del buildenv
Remove this line pls, since there is no buildenv anymore.

2022-05-06 07:43 UTC, byewokko commented on Dockerfile.test
> +#   py3-pip
This doesn't have to be here either.

2022-05-06 17:57 UTC, ateska commented
As discussed, we need some hard numbers here - size of images + size of the base image (alpine).

2022-05-10 10:22 UTC, sedoy26 commented
@byewokko @ateska

2022-05-10 10:23 UTC, sedoy26 commented
@byewokko @ateska 
original image size: 238MB
two stage image size: 218MB
alpine image size: 5.61MB

2022-05-10 11:53 UTC, ateska commented
Hmms, not great, not terrible.
Let's merge this, we can investigate later how to reduce the size futher if needed.

2022-05-11 20:40 UTC, byewokko approved these changes

2022-05-19 17:35 UTC, merged