Documentation restructure and UI guide
TeskaLabs/seacat-auth pull request #338
Opened 2024-01-10 14:27 UTC by avglassman

With Robin, I've reorganized the documentation, and we've identified some pages that need to be written.

New here:
* Structure: Documentation now has top-bar sections. The more technical (installation, config, etc) is in the Administration guide, and less technical info (UI maneuvers, for now) are in the User guide. The pages have been reorganized/regrouped and lightly edited for clarity.
* The User guide: It's new and quite simple, definitely room for improvement in the future.

I created several pages for Robin and myself to write/co-write when there's time, and once those are ready, this can be the future structure: 
[Proposed documentation nav tree.md](https://github.com/TeskaLabs/seacat-auth/files/13888903/Proposed.documentation.nav.tree.md)

I suspect we may reorganize a bit yet again (mainly to more effectively group information about credentials, tenants, resources, roles etc that is currently present in multiple categories), but for now, I believe that this will be easier to work with. 🙂

2024-01-10 15:33 UTC, byewokko requested changes
thanks, this looks great! i have some remarks about the User guide, please see the relevant comment

2024-01-10 15:33 UTC, byewokko commented on mkdocs.yml
> +      - user/sessions.md
in my view, the User guide is meant for common users who use seacat auth only for logging in and possibly updating their own account settings (email address, passwords etc.). they don't need to know anything about credentials, resources or tenants - all of that is admin stuff.

i think we should only have two pages here - one about login and the other about account settings.

the rest should probably go to the configuration section (for now at least)

2024-01-10 15:33 UTC, byewokko commented on .DS_Store
these .DS_Store files shouldn't be part of the merge request :ghost:

2024-01-11 11:55 UTC, ateska approved these changes
Let's merge this to see that live

2024-01-11 17:07 UTC, byewokko commented
an idea: we could group the basic admin UI pages such as managing tenants, roles and resources under a new section called "Access control". i 'd say access control is all that most admins want from seacat auth.

2024-01-14 20:16 UTC, avglassman commented
Updated - Now there is an **Administration guide** section and an **Account help** section (new documents added there, as we discussed). Aleš already approved, @byewokko can we merge and see?

2024-01-15 09:17 UTC, byewokko approved these changes
nice, let's merge it!

2024-01-15 10:58 UTC, merged