Implement OAuth refresh tokens
TeskaLabs/seacat-auth pull request #358
Opened 2024-03-28 16:30 UTC by byewokko

closes #154

2024-04-23 12:14 UTC, byewokko commented on seacatauth/cookie/handler.py
> +			# TODO: Why is this here????????? Add comment!
solve this!

2024-04-23 12:20 UTC, ateska requested changes
After this, please merge and test properly.

2024-04-23 12:20 UTC, ateska commented on seacatauth/client/service.py
> +from seacatauth import exceptions
Relative import.

2024-05-16 14:11 UTC, byewokko commented on seacatauth/cookie/handler.py
> +			# TODO: Why is this here????????? Add comment!
cookie needs to be set for any kind of session

2024-05-16 14:12 UTC, merged