Tenant search filter
TeskaLabs/seacat-auth pull request #49
Opened 2022-06-14 14:00 UTC by byewokko

`GET /tenants` allows for matching tenants on a substring using query parameter `f=<substring>`.

2022-06-15 23:21 UTC, ateska requested changes

2022-06-15 23:21 UTC, ateska commented on seacatauth/tenant/providers/mongodb.py
> +				]}}},
I don't get this query ...

2022-06-16 09:55 UTC, byewokko commented on seacatauth/tenant/providers/mongodb.py
> +				]}}},
Added explanation in code

2022-06-17 01:36 UTC, ateska approved these changes

2022-06-20 15:19 UTC, merged